[project]
name = "dota2uid-host-entry"
version = "0.1.0a3"
requires-python = ">=3.12"
dependencies = ["dota2forge-core[stratz]==0.1.0a3", "dota2forge-renderer==0.1.0a3", "dota2uid[stratz]==0.1.0a3", "httpx>=0.28.1,<1", "pillow>=11.3,<13"]
gscore_auto_update_dep = ["dota2forge-core[stratz]==0.1.0a3", "dota2forge-renderer==0.1.0a3", "dota2uid[stratz]==0.1.0a3"]
